# Generated by Django 5.1.1 on 2024-10-19 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "membre"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_record",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsultationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("establishment", models.CharField(max_length=100)),
                ("symptoms", models.TextField()),
                ("diagnosis", models.TextField()),
                ("prescriptions", models.TextField(blank=True)),
                ("treatments", models.TextField(blank=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "medecin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="dossier_medical.medicalrecord",
                    ),
                ),
            ],
        ),
    ]
