# Generated by Django 5.1.1 on 2024-10-18 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facility",
                    models.CharField(
                        blank=True,
                        help_text="The consultation facility or 'Online' for virtual consultations.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("consultation_date", models.DateField()),
                ("consultation_start_time", models.TimeField()),
                ("consultation_end_time", models.TimeField()),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "medecin"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations_as_doctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "membre"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations_as_patient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
