# Generated by Django 5.1.1 on 2024-10-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning_consultation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultation",
            name="consultation_date",
        ),
        migrations.AlterField(
            model_name="consultation",
            name="consultation_end_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="consultation_start_time",
            field=models.DateTimeField(),
        ),
    ]
