# Generated by Django 5.1.1 on 2024-10-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_is_online_customuser_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("membre", "Membre"), ("medecin", "Médecin"), ("bot", "Bot")],
                default="membre",
                max_length=10,
            ),
        ),
    ]
