# Generated by Django 5.1.1 on 2024-10-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="seen",
            field=models.BooleanField(default=False),
        ),
    ]
